#![no_std]
use soroban_sdk::{contract,contractimpl,contracttype,Address,BytesN,Env,Symbol};
#[contracttype] #[derive(Clone)] pub enum Key{Head(BytesN<32>),Event(BytesN<32>)}
#[contracttype] #[derive(Clone,Debug,Eq,PartialEq)] pub struct Head{pub custodian:Address,pub hash:BytesN<32>,pub sequence:u32,pub timestamp:u64}
#[contracttype] #[derive(Clone,Debug,Eq,PartialEq)] pub struct Transfer{pub version:BytesN<32>,pub from:Address,pub to:Address,pub previous_hash:BytesN<32>,pub event_hash:BytesN<32>,pub timestamp:u64,pub sequence:u32}
#[contract] pub struct CustodyRegistry;
#[contractimpl]
impl CustodyRegistry {
 pub fn __constructor(env:Env,controller:Address){env.storage().instance().set(&Symbol::new(&env,"controller"),&controller);}
 pub fn register(env:Env,version:BytesN<32>,custodian:Address,initial_hash:BytesN<32>){let controller:Address=env.storage().instance().get(&Symbol::new(&env,"controller")).unwrap();controller.require_auth();let key=Key::Head(version);assert!(!env.storage().persistent().has(&key),"already registered");env.storage().persistent().set(&key,&Head{custodian,hash:initial_hash,sequence:0,timestamp:0});env.storage().persistent().extend_ttl(&key,10000,100000);}
 pub fn transfer(env:Env,event_ref:BytesN<32>,version:BytesN<32>,from:Address,to:Address,previous_hash:BytesN<32>,event_hash:BytesN<32>,timestamp:u64){from.require_auth();let key=Key::Head(version.clone());let mut head:Head=env.storage().persistent().get(&key).unwrap();if let Some(old)=env.storage().persistent().get::<_,Transfer>(&Key::Event(event_ref.clone())){assert!(old.version==version&&old.from==from&&old.to==to&&old.event_hash==event_hash&&old.previous_hash==previous_hash&&old.timestamp==timestamp,"conflicting retry");return;}assert!(head.custodian==from,"not expected custodian");assert!(head.hash==previous_hash,"stale custody head");assert!(timestamp>=head.timestamp&&timestamp<=env.ledger().timestamp(),"invalid timestamp");assert!(from!=to,"same custodian");head.sequence+=1;let event=Transfer{version,from,to:to.clone(),previous_hash,event_hash:event_hash.clone(),timestamp,sequence:head.sequence};head.custodian=to;head.hash=event_hash;head.timestamp=timestamp;let ek=Key::Event(event_ref.clone());env.storage().persistent().set(&ek,&event);env.storage().persistent().set(&key,&head);env.storage().persistent().extend_ttl(&ek,10000,100000);env.storage().persistent().extend_ttl(&key,10000,100000);env.events().publish((Symbol::new(&env,"transfer"),event_ref),event);}
 pub fn head(env:Env,version:BytesN<32>)->Option<Head>{env.storage().persistent().get(&Key::Head(version))}
 pub fn event(env:Env,event_ref:BytesN<32>)->Option<Transfer>{env.storage().persistent().get(&Key::Event(event_ref))}
}
#[cfg(test)] mod tests{use super::*;use soroban_sdk::testutils::Address as _;#[test]fn sequence_and_stale_head(){let e=Env::default();e.mock_all_auths();let a=Address::generate(&e);let b=Address::generate(&e);let id=e.register(CustodyRegistry,(&a,));let c=CustodyRegistryClient::new(&e,&id);let v=BytesN::from_array(&e,&[1;32]);let h=BytesN::from_array(&e,&[2;32]);let nh=BytesN::from_array(&e,&[3;32]);c.register(&v,&a,&h);c.transfer(&h,&v,&a,&b,&h,&nh,&0);assert_eq!(c.head(&v).unwrap().sequence,1);assert!(c.try_transfer(&nh,&v,&a,&b,&nh,&h,&0).is_err());assert!(c.try_transfer(&nh,&v,&b,&a,&h,&nh,&0).is_err());}#[test]fn unauthorized_registration_fails(){let e=Env::default();let a=Address::generate(&e);let id=e.register(CustodyRegistry,(&a,));let c=CustodyRegistryClient::new(&e,&id);let h=BytesN::from_array(&e,&[1;32]);assert!(c.try_register(&h,&a,&h).is_err());}}
